### ISSUE TITLE
Mirasvit Google Tag Manager module not working when Turbo Mode ON

### ISSUE THREAD

**Issue by ShubWCL** [breezefront/module-breeze-integrations#1]
When we turn ON Turbo Mode and make our site SPA, the tracking is not working. 
We are using Mirasvit Google Tag Manager which is listed under Breeze-compatible modules with Magento 2 but it doesn't work. 

Module link: https://mirasvit.com/magento-2-google-tag-manager.html

**Comment by vovayatsyuk** [comment]
Can you try this solution? https://github.com/breezefront/community/discussions/22#discussioncomment-3971268

**Comment by vovayatsyuk** [comment]
I don't know why it's not working for you. Please share the link to your site.

**Comment by ShubWCL** [comment]
We are using Mirasvit module and Turbo Mode is ON. 
But we are not getting tracking results, events being fired, etc.

**Comment by sandipansaha** [comment]
Hi Yatsyuk,

The module has the latest version pushed very recently. Could it be something that has not been added to the breeze integration yet?
https://mirasvit.com/docs/module-gtm/current/changelog
Please check.

Thanks

**Comment by vovayatsyuk** [comment]
Looks like this commit should fix it: https://github.com/breezefront/module-breeze-integrations/commit/0a5a7a446c4495e6ba5c0ed4fb546f2732d5f5dd

**Comment by sandipansaha** [comment]
Hi Yatsyuk,

That is great, will you push that to the module (private repo) soon or should I create a patch?

Thanks

**Comment by vovayatsyuk** [comment]
> The module has the latest version pushed very recently.

The version I have is not sending cart events. Can you enable breeze debug mode in the settings so I could see the sources of the original module at your site?

**Comment by sandipansaha** [comment]
Hi Yatsyuk,

Debug mode is enabled now.
![image](https://user-images.githubusercontent.com/4614581/214570301-76f37445-950a-4d1b-a392-9122492b306d.png)

We are using swissup/module-breeze-integrations : 1.2.7
It does not have the commit https://github.com/breezefront/module-breeze-integrations/commit/0a5a7a446c4495e6ba5c0ed4fb546f2732d5f5dd
![image](https://user-images.githubusercontent.com/4614581/214570660-d8d7ac0a-b1b1-4612-b009-ce529377195f.png)

Thanks

**Comment by sandipansaha** [comment]
Hi Yatsyuk,

> The version I have is not sending cart events.

You need the latest version for that https://mirasvit.com/docs/module-gtm/current/changelog#1-2-46

Thanks

**Comment by vovayatsyuk** [comment]
I don't have the latest version of mirasvit module and I wanted to see it on your site. But when I add ?breeze=0 to the URL I still see the breeze scripts.

I can't fix it without mirasvit sources.

**Comment by sandipansaha** [comment]
Hi Yatsyuk,

Works for me. Try URL
IMAGE

Thanks

**Comment by vovayatsyuk** [comment]
Looks like adding to cart event is working fine in breeze on your store. Please confirm and I will create a new tag for this module 👍

**Comment by ShubWCL** [comment]
Thanks for the update. I checked but below are the problems are still facing:
1. When we visit from one page to another the URL is not being tracked in GA. 
For ex: If I am on Homepage and then go to the product page or category page. But in GA it still shows Homepage. 
Thus this is affecting tracking. 

2. The data layers are not giving details like product impression, product detail, category detail, etc. and thus affecting tracking
3. "Add to cart" event seems working but other events like add to wishlist, remove from cart, increase quantity, decrease the quantity, etc. are not working properly with Turbo mode on. 
4. The "Quick view" feature of the Breeze theme is not working and tracking too.

**Comment by vovayatsyuk** [comment]
Can you guide me on how to configure GTM so all of this additional details will be sent?

For me even on Luma this info is not sent. I just see the category name in page_view requests.

**Comment by vovayatsyuk** [comment]
I mean, what should I add in GTM tags to make requests with all details? 

This is my current setup:

<img width="1277" alt="CleanShot 2023-01-27 at 15 59 52@2x" src="https://user-images.githubusercontent.com/306080/215104770-deadeb29-c82a-40ae-b935-cff098b4f636.png">

And this is what I get during page views:

<img width="983" alt="CleanShot 2023-01-27 at 16 00 35@2x" src="https://user-images.githubusercontent.com/306080/215104927-61988108-ace8-498e-b733-e21801ec9252.png">

But on your site there are much more data in this request:

<img width="1272" alt="CleanShot 2023-01-27 at 16 02 31@2x" src="https://user-images.githubusercontent.com/306080/215105334-1825ccd5-72da-4a91-bf0f-3d42551cdc0c.png">

**Comment by vovayatsyuk** [comment]
Just figured out how to configure GTM do send additional data. The following checkbox in "More Settings" did the job:

<img width="374" alt="CleanShot 2023-01-27 at 16 08 07@2x" src="https://user-images.githubusercontent.com/306080/215106526-14ff6b99-3f09-4968-9d2a-316d6a89904e.png">

**Comment by vovayatsyuk** [comment]
Okay. After I configured GTM, I see that requests are sent with all data. With and without turbo.

Here is my GTM configs:

<img width="1000" alt="CleanShot 2023-01-27 at 16 15 45@2x" src="https://user-images.githubusercontent.com/306080/215108084-42b9c2bf-86bc-4c1c-90ab-51da46129683.png">

![CleanShot 2023-01-27 at 16 17 21@2x](https://user-images.githubusercontent.com/306080/215108373-48f898c0-5124-4d94-a7b2-b5a681a8ba9c.png)

**Comment by ShubWCL** [comment]
> Okay. After configuring GTM, I see requests are sent with all data. With and without turbo.
> 
> Here is my GTM configs:
> 
> <img alt="CleanShot 2023-01-27 at 16 15 45@2x" width="1000" src="https://user-images.githubusercontent.com/306080/215108084-42b9c2bf-86bc-4c1c-90ab-51da46129683.png">
> 
> ![CleanShot 2023-01-27 at 16 17 21@2x](https://user-images.githubusercontent.com/306080/215108373-48f898c0-5124-4d94-a7b2-b5a681a8ba9c.png)

Hi, Can you share your email address with me, where I can add you to the gtm and you can see things from Mirasvit tags/triggers on your end as well and you can debug easily?

**Comment by vovayatsyuk** [comment]
1. Do you have similar settings in your GTM?
2. Do you have the site with turbo enabled? Please share it with me.
3. My email is -

**Comment by ShubWCL** [comment]
> * Do you have similar settings in your GTM?
Yes, we have. You can see all our tags, triggers, etc once you open our GTM account.
> * Do you have the site with turbo enabled? Please share it with me.
Yes we have enabled it on 
> * My email is -
Have sent the invite, please check.

_Let me know once you have everything to debug. 
You can test GTM debug view by doing multiple events as a user._

**Comment by vovayatsyuk** [comment]
I see that all requests are sent successfully:

https://user-images.githubusercontent.com/306080/215428694-8db1ae1c-a960-41da-9de2-a7d7ca70a285.mp4

**Comment by ShubWCL** [comment]
> I see that all requests are sent successfully:
> 
>  CleanShot.2023-01-30.at.10.35.40.mp4

Hi, we have shared the GTM access on your email address for below two stores (.com and .eu). 

Video link using **Breeze** theme: 
Staging link: 
Description: As per this video you can see below points:

- The page is not loading and thus it is not updating on Google Analytics. 
_For example: If I go from the homepage to category/product page (Turbo Mode Enabled), it doesn't change the URL in Google Analytics. In GA it is still the homepage and thus it is affecting the tracking.

If we try to visit the Cart page or Checkout page it loads like the normal page (no ajax loading) and thus you can see those URLs in Google tracking._ 

Video link using **Luma** theme: 
Staging link: 
You can see the difference in page loading, as when we visit from one page to another the URL is being fetched correctly in GA and thus tracking is working with events.

Please let me know if you have any ques.

**Comment by vovayatsyuk** [comment]
Try to add "History Change" trigger to GA config tag:

<img src="https://user-images.githubusercontent.com/306080/215987516-4b5b976e-e2d4-4592-a734-0895e56c3c0c.png" width="588"/>

**Comment by ShubWCL** [comment]
Hi below are some issues we found:

1. When Breeze theme Turbo Mode OFF and Mirasvit module is used for Google tracking and Amasty Facebook pro for pixel tracking

**What we found**: We found that multiple/duplicate "add-to-cart" events are being fired. 

The website we used for debugging is 

Please watch the video below for detail:

Video link: https://www.loom.com/share/df18042beac74dda95f22ae559baf852 

2. When Breeze theme Turbo Mode ON and Mirasvit module is used for Google tracking and Amasty Facebook pro for pixel tracking

**What we found**:  We found duplicate add-to-cart or remove-from-cart events. To check this please add around 5-6 products to the cart and use the GTM debug method and pixel helper chrome extension in order to check its working. 

The website we used for debugging is

Please watch the video below for detail:

Video link: https://www.loom.com/share/c97d40f67cc5486a91818be795d2328d

SPECIAL NOTE: In addition to the above points, GTM debug window is not loading another page when Turbo Mode is ON.

**Comment by vovayatsyuk** [comment]
Sorry, but I'm not able to reproduce these issues locally (I'm using swissup modules and mirasvit google tag). Please add the exact steps I need to do. eg: 

1. Open category
2. Open ajaxpro quick view
3. Press add to cart
4. ...

p.s. We do not have integration with amasty facebook module.

**Comment by ShubWCL** [comment]
@vovayatsyuk please try to do multiple events of add to cart, and other enhanced ecom. as I did in the video shared with you. 
Let me know if you are still not able to reproduce those incidents. 
And please share a video of your demo so I can correlate it.

**Comment by vovayatsyuk** [comment]
https://youtu.be/_DTeaadtJ5s

**Comment by ShubWCL** [comment]
@vovayatsyuk thanks for the vide, found that two add_to_cart event from your video, shared screenshot. 

![image](https://user-images.githubusercontent.com/123495623/218422283-004d51f8-2b6a-4cd0-8ba9-43b533458c71.png)

**Comment by vovayatsyuk** [comment]
I don't see how it differs from behavior on Luma theme without any swissup modules:

https://user-images.githubusercontent.com/306080/218426070-635170cc-393b-43b0-b9d0-d6d35d0bea37.mp4

**Comment by ShubWCL** [comment]
@vovayatsyuk hi, didn't got you on your previous video of luma. 
It's just add to cart I found so far which is behaving multiples and the same data it is sending to google which is why the data is not accurate over google analytics. 

For ex: If user added 5 times add to cart but in google analytics it is showing 15 times. thus the data is wrong and inaccurate. 

Let me know if you want to have a call to discuss real-time, that will work best. 
or if you need any extra input or scenarios from me.

**Comment by vovayatsyuk** [comment]
Please post short steps to reproduce the issue because I can't reproduce it.

**Comment by ShubWCL** [comment]
@vovayatsyuk  we did the updates as per your documented guide but we are facing issues with our staging environment. 

Below are the details:

We updated the modules as per this for Mirasvit Tag Manager: https://breezefront.com/extensions

![image](https://user-images.githubusercontent.com/123495623/225842413-0cf73d99-5bf4-43af-b19e-c764d90cb489.png)

But we are facing JS errors, the "add to cart" section is wiped out from PDP, no pricing, CSS issues etc.

**Comment by vovayatsyuk** [comment]
1. `Uncaught SyntaxError: Identifier 'RangeSlider' has already been`. This error is caused by old Ajaxlayaered navigation module. Please update.
2. `Uncaught TypeError: quotes.eq(...).fadeIn(...).delay is not a function`. This is some custom code from your theme:

    ```js
    (function() {
        var quotes = $(".quotes");
        var quoteIndex = -1;
        function showNextQuote() {
            ++quoteIndex;
            quotes.eq(quoteIndex % quotes.length).fadeIn(2000).delay(4000).fadeOut(2000, showNextQuote);
        }
        showNextQuote();
    }
    )();
    ```
3. `TypeError: Cannot read properties of undefined (reading 'getJson')`. This error is caused by the jQuery script. Breeze doesn't allow to include jquery without breaking other functionality because we have our own functions in `$` namespace.

**Comment by ShubWCL** [comment]
thanks, @vovayatsyuk  for the update but upon updating all related modules in the Breeze. 
We are still seeing in GTM debug view that when we are on the "Cart page" and "Checkout page", both these pages' add to cart event/tag is firing again.

Add to cart event/tag should only fire when the user clicks on add to cart button. But in this case, here it is auto-firing again in the Cart page and Checkout page. 

Please fix this on theme. 
We are using module: https://mirasvit.com/magento-2-google-tag-manager.html

**Comment by vovayatsyuk** [comment]
Interesting. Have you checked the default behavior with the Luma theme? I'm asking this because Breeze is disabled at the cart and checkout pages (fallback to default Luma stack is used).

**Comment by ShubWCL** [comment]
@vovayatsyuk this is what Mirasvit support is saying:

![image](https://user-images.githubusercontent.com/123495623/228160737-5cec6339-e8b8-4372-b45a-2988275b166b.png)

**Comment by vovayatsyuk** [comment]
But I was asking you about behavior at the Luma theme.

**Comment by vovayatsyuk** [comment]
I just tested it on my local setup with BreezeEvolution, and I can't reproduce this issue. Here is my steps:

1. Open homepage
2. Navigate to bags
3. Add bag to the cart
4. Open another product
5. Add it to the cart
6. Navigate to the cart page
7. Navigate to the checkout page

And here is the summary of all events from tag assistant:

![image](https://user-images.githubusercontent.com/306080/228164441-36c35e0a-7c8e-4fdb-9ef0-d24741c27265.png)

Everything seems correct: 2 add to cart events, 1 list view, 1 item view.

**Comment by ShubWCL** [comment]
@vovayatsyuk I swtiched to Luma theme and still the same issue. 

You can check this site and do the below steps:

- Add a product to cart from product single page (one time add to cart event will fire)
- Add another product (two times same add to cart event will fire)
- Go to cart page (you will see add to cart events being fired again)
- Go to checkout page (you will see add to cart events being fired again)

Note: please share your email so we can add you to Google Tag Manager account and you can do the debug from your end too.

Site for ref: https://mcstaging.target-darts.uk/

**Comment by vovayatsyuk** [comment]
Your Luma still has a lot of modules, you need to disable all modules except mirasvit tag manager and try again. 

If the bug will remain after that, open a ticket in mirasvit support.
If the bug will disappear, enable modules one by one to find the causer.
