### ISSUE TITLE
Do you have plan to integrate with amasty advance review module?

### ISSUE THREAD

**Issue by hungdq123** [breezefront/module-breeze-integrations#3]

**Comment by dimdimich** [comment]
Hi,

We have received one inquiry from one of our customers regarding Breeze integration with this module. We are currently in the process of reviewing this request. Could you please contact Amasty and inquire about the possibility of integrating Breeze from their end? The more inquiries they receive, the higher the chances that they will add Breeze integration to their system, which would be highly beneficial for the Breeze community. Thank you.

**Comment by hungdq123** [comment]
> Hi,
> 
> We have received one inquiry from one of our customers regarding Breeze integration with this module. We are currently in the process of reviewing this request. Could you please contact Amasty and inquire about the possibility of integrating Breeze from their end? The more inquiries they receive, the higher the chances that they will add Breeze integration to their system, which would be highly beneficial for the Breeze community. Thank you.

I have contacted but they recommend to contact Breeze team

**Comment by dimdimich** [comment]
Please post your request to https://github.com/breezefront/community/discussions/categories/3-integrations but we would really appreciate if you will try to contact Amasty one more time
